<?php

/**
 * @file
 * Contains token_auth.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function token_auth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the token_auth module.
    case 'help.page.token_auth':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The OAuth 2.0 Authorization Framework: Bearer Token Usage') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function token_auth_cron() {
  /* @var \Drupal\Core\Entity\EntityManagerInterface $manager */
  $manager = \Drupal::service('entity.manager');
  $storage = $manager->getStorage('access_token');
  $query = $storage->getQuery();
  $ids = $query
    ->condition('expire', REQUEST_TIME, '>')
    ->execute();
  if (!empty($ids)) {
    $storage->delete($storage->loadMultiple($ids));
  }
}

/**
 * Implements hook_theme().
 */
function token_auth_theme($existing, $type, $theme, $path) {
  return [
    'access_token' => [
      'render element' => 'access_token',
      'file' => 'access_token.page.inc',
    ],
  ];
}
