<?php

/**
 * @file
 *
 * Module implementation file.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function simple_oauth_3p_form_oauth2_token_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['use_implicit'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable the implicit grant?'),
    '#description' => t('The implicit grant has the potential to be used in an insecure way. Only enable this if you understand the risks. See https://tools.ietf.org/html/rfc6819#section-4.4.2 for more information.'),
    '#default_value' => \Drupal::config('simple_oauth_3p.settings')->get('use_implicit'),
  ];
  $form['#submit'][] = 'simple_oauth_3p_form_oauth2_token_settings_submit';
}

/**
 * Form submission handler.
 *
 * @param array $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function simple_oauth_3p_form_oauth2_token_settings_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $settings = \Drupal::configFactory()->getEditable('simple_oauth_3p.settings');
  $settings->set('use_implicit', $form_state->getValue('use_implicit'));
  $settings->save();
}
